name: genvideo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cffi=1.17.1
  - cpython=3.10.17
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - intel-openmp=2022.0.1
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.0.30
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.24
  - libdrm=2.4.124
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.24.1
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpciaccess=0.18
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - p11-kit=0.24.1
  - pip=25.1.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.17
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=80.1.0
  - svt-av1=1.4.1
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.13.2
  - wayland=1.23.1
  - wayland-protocols=1.44
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - accelerate==0.26.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - audioread==3.0.1
      - biopython==1.85
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclassy==1.0.1
      - debugpy==1.8.14
      - decorator==4.4.2
      - diffusers==0.27.2
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - git-filter-repo==2.47.0
      - greenlet==3.2.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.21.4
      - idna==3.4
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==8.36.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jiter==0.9.0
      - joblib==1.5.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - kneed==0.8.5
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - moviepy==1.0.3
      - msgpack==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.24.4
      - openai==1.77.0
      - openai-whisper==20240930
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - praatio==6.2.0
      - proglog==0.1.11
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.28.1
      - rich==14.0.0
      - rich-click==1.8.8
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.40
      - stack-data==0.6.3
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.15.2
      - tornado==6.5
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.36.2
      - triton==2.1.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - zipp==3.21.0
