name: gen_video
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.49.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.10.17
  - readline=8.2
  - setuptools=80.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.3.0
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.4
      - aiosignal==1.3.2
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.4.0
      - baize==0.22.2
      - cachetools==6.0.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - coloredlogs==15.0.1
      - comm==0.2.2
      - crcmod==1.7
      - cryptography==45.0.3
      - ctranslate2==4.6.0
      - datasets==2.18.0
      - debugpy==1.8.14
      - decorator==4.4.2
      - diffusers==0.33.1
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - editdistance==0.8.1
      - einops==0.8.1
      - einx==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.115.12
      - faster-whisper==1.1.1
      - ffmpy==0.5.0
      - filelock==3.13.1
      - fish-speech==0.1.0
      - flatbuffers==25.2.10
      - frozendict==2.4.6
      - frozenlist==1.6.0
      - fsspec==2024.2.0
      - funasr==1.1.5
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==8.36.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.4
      - jiter==0.10.0
      - jmespath==0.10.0
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kaldiio==2.18.1
      - kui==1.9.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - loguru==0.7.3
      - loralib==0.1.2
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelscope==1.17.1
      - more-itertools==10.7.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnxruntime==1.22.0
      - openai==1.82.0
      - openai-whisper==20240930
      - opencc-python-reimplemented==0.1.7
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - oss2==2.19.1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pyarrow-hotfix==0.7
      - pyaudio==0.2.14
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyrootutils==1.0.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.1.post0
      - pytorch-wpe==0.0.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.32.3
      - resampy==0.4.3
      - rich==14.0.0
      - ruff==0.11.11
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - silero-vad==5.1.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.6.0+cu118
      - torch-complex==0.4.4
      - torchaudio==2.6.0+cu118
      - torchmetrics==1.7.2
      - torchvision==0.21.0+cu118
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.2.0
      - typer==0.16.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - vector-quantize-pytorch==1.14.24
      - wandb==0.19.11
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.22.0
      - zstandard==0.23.0
