# 基础配置
base:
  # 资源文件存放目录
  output_dir: "./output"
  base_dir: "./output/temp"
  # 上传文件目录
  upload_dir: "./upload"
  # 故事名称
  story_name: "default"
  # 手动分段
  manual_clip_story: false

# 文件配置
files:
  # 音频文件名
  audio:
    raw: "新录音.m4a"
    mp3: "audio.mp3"
  # 文本文件名
  text:
    story: "story.txt"
    split_story: "split_story.json"
    scene_prompts: "scene_prompts.json"
    subtitles: "subtitles.json"
  # 图片和视频目录
  media:
    image_dir: "images"
    output_video: "output_video.mp4"

model:
  llm: "deepseek" # 可选值: "deepseek"
  img: 
    use_api: false
    api: "gpt-image-1" # 可选值: "gpt-image-1", "dall-e-3", "dall-e-2"
    offline: "taiyi-sd" # 可选值: "taiyi-sd"
