# 基础配置
base:
  resources_dir: "resources"
  # 资源文件存放目录
  output_dir: "output"
  base_dir: "output/temp"
  # 上传文件目录
  upload_dir: "upload"
  # 故事名称
  story_name: "default"
  # 手动分段
  manual_clip_story: false
  use_tts: false

# 文件配置
files:
  resources:
    font: "NotoSansCJK-Regular.ttc"
  # 音频文件名
  audio:
    raw: "fake.wav"
    mp3: "audio.mp3"
  # 文本文件名
  text:
    story: "story.txt"
    split_story: "split_story.json"
    raw_scene_prompts: "raw_scene_prompts.json"
    scene_prompts: "scene_prompts.json"
    asr_result: "asr_result.json"
    subtitles: "subtitles.json"
    subtitles_matched_scenes: "subtitles_matched_scenes.json"
    split_story_matched_subs: "split_story_matched_subs.json"
  # 图片和视频目录
  media:
    image_dir: "images"
    output_video: "output_video.mp4"
  reference:
    speaker_path: "resources/reference/speaker"

model:
  tts:
    path: "resources/models/tts"
    model_dir_name: "fish-speech" # 可选值: "fish-speech-1.5"
    use_reference_speaker: true
    use_compile: true
    num_samples: 4
    codes: "1" # 可选值: 从0到num_samples-1
  asr:
    model: "whisper" # 可选值: "whisper"
    whisper: "large" # 可选值: "tiny", "base", "small", "medium", "large", "turbo"
  llm:
    model: "deepseek" # 可选值: "deepseek"
    align_batch_size: 32
    generate_batch_size: 12
  img:
    use_api: false
    api: "gpt-image-1" # 可选值: "gpt-image-1", "dall-e-3", "dall-e-2"
    quality: "low" # 可选值: "low", "high", "medium"
    offline: "taiyi-sd" # 可选值: "taiyi-sd"

function:
  bg_mode: "dynamic" # 可选值: "dynamic", "no_bg"
